### PR TITLE
Fix: Key combinations in SearchDialog component not working on Mac #22

### PR DESCRIPTION
**Pull request by AhmetSBulbul**
I have added control key option and tested, everything works as expected on mac. Also I didn't change the previous solution so on Windows it should be still works. Solves the issue #22 .

### CODE REVIEW

**Comment by ozhanefemeral** [comment]
I tested on both platforms and it's looking good 💪

after applying some minor changes we can ship

**Comment by AhmetSBulbul** [comment]
@ozhanefemeral I updated the PR as Ready for Review do we need any change in this branch?

**Comment by ozhanefemeral** [comment]
I requested 2 minor changes and we can merge it after handling them

**Comment by AhmetSBulbul** [comment]
@ozhanefemeral Done. But I didn't understand, isn't CTRL used for tab change on Windows? Or should I use Alt for windows and CTRL for MacOS without or condition? Sorry for bothering, I'm asking it because we've discussed before testing. Sorry for bothering, I want to be sure about it.

**Comment by ozhanefemeral** [comment]
Hahah no need to worry! When I tested that on Windows, that tab change did not trigger **<ins>when we have dialogs open</ins>**. When dialog(s) are not open users can still navigate tabs using CTRL + 1-9.

I don't know what causes that but I am happy that we can use shortcuts on Mac too so lets push forward 🤞

**Review by ozhanefemeral — APPROVED** [review]

**Comment by AhmetSBulbul** [comment]
@ozhanefemeral Haha, the reviews just dropped. I guess you forgot to submit the review.

**Pull request merged**
